### PR TITLE
Responsive theme upgrade design 2016

### LINKED ISSUE #27: Update theme from new design
Designs in https://invis.io/2880QJIJH, resources in https://groups.google.com/a/mysociety.org/forum/?hl=en-GB#!topic/alaveteli/wJAp1GPuXcw

### PR DESCRIPTION
**Pull request by wrightmartin**
Fixes #27 

This adds new styles and design elements for the IPV alaveteli theme.

screen shot 2016-11-21 at 17 17 24

### CODE REVIEW

**Comment by garethrees** [comment]
Looks great from my quick click around.

I think I'd go for slightly more contrast on the correspondence boxes. I found them a bit hard on my eyes (on my display at least).

screen shot 2016-11-23 at 12 29 46

**Comment by garethrees** [comment]
Currently waiting for feedback https://groups.google.com/a/mysociety.org/d/msg/alaveteli/kZHm1x48n1U/jF8cnNcQBwAJ

**Comment by wrightmartin** [comment]
I've added the remaining parts of the design (mostly grey boxes)

The main thing I didn't do, was on the authority page move the search function into the main column - this would require overriding a lot of the template and it didn't seem like we would be gaining much from doing this, compared to what we'd lose from updates to core Alaveteli)

**Comment by garethrees** [comment]
Also needs a grey box around the categories on http://staging.alaveteli.org/body/list/all

**Comment by garethrees** [comment]
Merged as 45d88a3

**Pull request closed without merging**
